# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("READ", "Consulter"),
                            ("COMMENT", "Commenter"),
                            ("WRITE", "Modifier"),
                            ("MANAGE", "Gerer"),
                        ],
                        default="READ",
                        max_length=10,
                    ),
                ),
                (
                    "inherit",
                    models.BooleanField(
                        default=True,
                        help_text="S'applique a tout le sous-arbre du dossier.",
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="storage.file",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions",
                        to="storage.folder",
                    ),
                ),
                (
                    "granted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "grantee_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_recues",
                        to="accounts.service",
                    ),
                ),
                (
                    "grantee_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="permissions_recues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "permission",
                "indexes": [
                    models.Index(
                        fields=["grantee_user", "folder"],
                        name="sharing_per_grantee_3ea50e_idx",
                    ),
                    models.Index(
                        fields=["grantee_service", "folder"],
                        name="sharing_per_grantee_447993_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("file__isnull", True), ("folder__isnull", False)),
                            models.Q(("file__isnull", False), ("folder__isnull", True)),
                            _connector="OR",
                        ),
                        name="permission_cible_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("grantee_service__isnull", True),
                                ("grantee_user__isnull", False),
                            ),
                            models.Q(
                                ("grantee_service__isnull", False),
                                ("grantee_user__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="permission_beneficiaire_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(editable=False, max_length=64, unique=True)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("READ", "Consulter"),
                            ("COMMENT", "Commenter"),
                            ("WRITE", "Modifier"),
                            ("MANAGE", "Gerer"),
                        ],
                        default="READ",
                        max_length=10,
                    ),
                ),
                ("password_hash", models.CharField(blank=True, max_length=255)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("max_downloads", models.PositiveIntegerField(blank=True, null=True)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("is_revoked", models.BooleanField(default=False)),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens",
                        to="storage.file",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liens",
                        to="storage.folder",
                    ),
                ),
            ],
            options={
                "verbose_name": "lien de partage",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("file__isnull", True), ("folder__isnull", False)),
                            models.Q(("file__isnull", False), ("folder__isnull", True)),
                            _connector="OR",
                        ),
                        name="lien_cible_unique",
                    )
                ],
            },
        ),
    ]
