# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PARTAGE_RECU", "Un element vous a ete partage"),
                            (
                                "NOUVEAU_FICHIER",
                                "Nouveau fichier dans un dossier suivi",
                            ),
                            ("NOUVELLE_VERSION", "Nouvelle version d'un fichier"),
                            ("COMMENTAIRE", "Nouveau commentaire"),
                            ("CONFLIT_SYNC", "Conflit de synchronisation"),
                            ("CONVERSION_TERMINEE", "Conversion terminee"),
                            ("QUOTA_PROCHE", "Quota bientot atteint"),
                        ],
                        max_length=25,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True)),
                ("target_type", models.CharField(blank=True, max_length=20)),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "notification",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read", "-created_at"],
                        name="notificatio_recipie_684eac_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PARTAGE_RECU", "Un element vous a ete partage"),
                            (
                                "NOUVEAU_FICHIER",
                                "Nouveau fichier dans un dossier suivi",
                            ),
                            ("NOUVELLE_VERSION", "Nouvelle version d'un fichier"),
                            ("COMMENTAIRE", "Nouveau commentaire"),
                            ("CONFLIT_SYNC", "Conflit de synchronisation"),
                            ("CONVERSION_TERMINEE", "Conversion terminee"),
                            ("QUOTA_PROCHE", "Quota bientot atteint"),
                        ],
                        max_length=25,
                    ),
                ),
                ("in_app", models.BooleanField(default=True)),
                ("email", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences_notif",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "type"), name="preference_unique"
                    )
                ],
            },
        ),
    ]
