# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeLog",
            fields=[
                ("seq", models.BigAutoField(primary_key=True, serialize=False)),
                ("entity_type", models.CharField(max_length=20)),
                ("entity_id", models.UUIDField(db_index=True)),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("CREATED", "Cree"),
                            ("UPDATED", "Modifie"),
                            ("MOVED", "Deplace"),
                            ("DELETED", "Supprime"),
                            ("RESTORED", "Restaure"),
                            ("PERMISSION", "Droits modifies"),
                        ],
                        max_length=15,
                    ),
                ),
                ("folder_path", models.TextField(blank=True, db_index=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changements",
                        to="accounts.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "changement",
                "ordering": ["seq"],
                "indexes": [
                    models.Index(
                        fields=["service", "seq"], name="sync_change_service_ae0647_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SyncOperation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "op_type",
                    models.CharField(
                        choices=[
                            ("CREATE_FOLDER", "Creation de dossier"),
                            ("RENAME", "Renommage"),
                            ("MOVE", "Deplacement"),
                            ("UPLOAD_VERSION", "Nouvelle version"),
                            ("DELETE", "Suppression"),
                            ("RESTORE", "Restauration"),
                            ("SET_METADATA", "Metadonnees"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(max_length=20)),
                ("target_id", models.UUIDField()),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("client_seq", models.BigIntegerField()),
                ("base_version", models.IntegerField(blank=True, null=True)),
                ("client_timestamp", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPLIED", "Appliquee"),
                            ("CONFLICT", "En conflit"),
                            ("REJECTED", "Rejetee"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "conflict_resolution",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SERVER_WINS", "Version serveur conservee"),
                            ("CLIENT_WINS", "Version hors ligne conservee"),
                            ("BOTH_KEPT", "Les deux versions conservees"),
                            ("MANUAL", "A arbitrer"),
                        ],
                        max_length=15,
                    ),
                ),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.TextField(blank=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations",
                        to="accounts.device",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operations_sync",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "operation de synchronisation",
                "ordering": ["device", "client_seq"],
                "indexes": [
                    models.Index(
                        fields=["device", "status"],
                        name="sync_syncop_device__3ef6b5_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="sync_syncop_status_c6ee02_idx",
                    ),
                ],
            },
        ),
    ]
