# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=200)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Connexion"),
                            ("LOGIN_FAILED", "Echec de connexion"),
                            ("LOGOUT", "Deconnexion"),
                            ("FILE_UPLOAD", "Televersement"),
                            ("FILE_DOWNLOAD", "Telechargement"),
                            ("FILE_VIEW", "Consultation"),
                            ("FILE_RENAME", "Renommage de fichier"),
                            ("FILE_MOVE", "Deplacement de fichier"),
                            ("FILE_DELETE", "Suppression de fichier"),
                            ("FILE_RESTORE", "Restauration de fichier"),
                            ("VERSION_RESTORE", "Restauration de version"),
                            ("FOLDER_CREATE", "Creation de dossier"),
                            ("FOLDER_RENAME", "Renommage de dossier"),
                            ("FOLDER_MOVE", "Deplacement de dossier"),
                            ("FOLDER_DELETE", "Suppression de dossier"),
                            ("FOLDER_RESTORE", "Restauration de dossier"),
                            ("PERMISSION_GRANT", "Attribution de droit"),
                            ("PERMISSION_REVOKE", "Retrait de droit"),
                            ("SHARE_LINK_CREATE", "Creation de lien"),
                            ("SHARE_LINK_ACCESS", "Acces par lien"),
                            ("SYNC_CONFLICT", "Conflit de synchronisation"),
                            ("USER_CREATE", "Creation de compte"),
                            ("USER_DISABLE", "Desactivation de compte"),
                            ("ROLE_CHANGE", "Changement de role"),
                            ("TRASH_PURGE", "Purge de la corbeille"),
                            ("GEO_CONVERT", "Conversion geospatiale"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=30)),
                (
                    "target_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("target_path", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=400)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites",
                        to="accounts.device",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activites",
                        to="accounts.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "entree de journal",
                "verbose_name_plural": "journal d'activite",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="audit_activ_actor_i_1f8acb_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_activ_action_f38451_idx",
                    ),
                ],
            },
        ),
    ]
