# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("DOCUMENT", "Document"),
                            ("IMAGE", "Image"),
                            ("TABLEUR", "Tableur"),
                            ("VECTEUR", "Donnees vectorielles"),
                            ("RASTER", "Donnees raster"),
                            ("CAO", "Plan CAO"),
                            ("ARCHIVE", "Archive"),
                            ("AUTRE", "Autre"),
                        ],
                        db_index=True,
                        default="AUTRE",
                        max_length=20,
                    ),
                ),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("description", models.TextField(blank=True)),
                ("is_locked", models.BooleanField(default=False)),
                ("locked_at", models.DateTimeField(blank=True, null=True)),
                ("extracted_text", models.TextField(blank=True, editable=False)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "locked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fichiers",
                        to="accounts.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "fichier",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("body", models.TextField()),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commentaires",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="storage.comment",
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="storage.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "commentaire",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version_number", models.PositiveIntegerField()),
                ("storage_key", models.CharField(max_length=500)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("checksum_sha256", models.CharField(db_index=True, max_length=64)),
                ("mime_type", models.CharField(blank=True, max_length=150)),
                ("comment", models.CharField(blank=True, max_length=500)),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("WEB", "Interface web"),
                            ("SYNC_OFFLINE", "Synchronisation hors ligne"),
                            ("IMPORT", "Import en masse"),
                        ],
                        default="WEB",
                        max_length=20,
                    ),
                ),
                ("client_id", models.UUIDField(blank=True, null=True)),
                ("is_conflict_copy", models.BooleanField(default=False)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="storage.file",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "version",
                "ordering": ["-version_number"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="current_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="storage.fileversion",
            ),
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=255, verbose_name="nom")),
                ("path", models.TextField(db_index=True, default="/", editable=False)),
                (
                    "depth",
                    models.PositiveIntegerField(
                        db_index=True, default=0, editable=False
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("icon", models.CharField(blank=True, max_length=40)),
                ("is_service_root", models.BooleanField(default=False)),
                ("size_bytes", models.BigIntegerField(default=0, editable=False)),
                ("file_count", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="storage.folder",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dossiers",
                        to="accounts.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "dossier",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="storage.folder",
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=60)),
                ("color", models.CharField(blank=True, max_length=20)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="accounts.service",
                    ),
                ),
            ],
            options={
                "verbose_name": "etiquette",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="fichiers", to="storage.tag"
            ),
        ),
        migrations.CreateModel(
            name="UploadSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("filename", models.CharField(max_length=255)),
                ("total_size", models.BigIntegerField()),
                ("chunk_size", models.PositiveIntegerField()),
                ("total_chunks", models.PositiveIntegerField()),
                ("received_chunks", models.JSONField(default=list)),
                ("checksum_sha256", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("EN_COURS", "En cours"),
                            ("TERMINE", "Termine"),
                            ("ANNULE", "Annule"),
                        ],
                        default="EN_COURS",
                        max_length=20,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=500)),
                ("client_id", models.UUIDField(blank=True, null=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="storage.file",
                    ),
                ),
                (
                    "folder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="storage.folder",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="televersements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "session de televersement",
            },
        ),
        migrations.CreateModel(
            name="FileMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(db_index=True, max_length=100)),
                ("value", models.TextField(blank=True)),
                ("value_type", models.CharField(default="texte", max_length=20)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUTO", "Extraite automatiquement"),
                            ("MANUEL", "Saisie par un agent"),
                        ],
                        default="MANUEL",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="storage.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "metadonnee",
                "indexes": [
                    models.Index(
                        fields=["key", "value"], name="storage_fil_key_d50391_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file", "key"), name="metadonnee_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="fileversion",
            constraint=models.UniqueConstraint(
                fields=("file", "version_number"), name="version_unique_par_fichier"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["parent", "is_deleted"], name="storage_fol_parent__0633e6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="folder",
            index=models.Index(
                fields=["service", "is_deleted"], name="storage_fol_service_f90cbd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("parent", "name"),
                name="dossier_nom_unique_par_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("service", "name"), name="tag_unique_service"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["folder", "is_deleted", "name"],
                name="storage_fil_folder__31f949_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=models.Index(
                fields=["kind", "is_deleted"], name="storage_fil_kind_722712_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="file",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="fichier_recherche_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="file",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_deleted", False)),
                fields=("folder", "name"),
                name="fichier_nom_unique_par_dossier",
            ),
        ),
    ]
