# Generated by Django 5.1.6 on 2026-09-06 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="kind",
            field=models.CharField(
                choices=[
                    ("DOCUMENT", "Document"),
                    ("CROQUIS", "Croquis"),
                    ("IMAGE", "Image"),
                    ("TABLEUR", "Tableur"),
                    ("VECTEUR", "Donnees vectorielles"),
                    ("RASTER", "Donnees raster"),
                    ("CAO", "Plan CAO"),
                    ("ARCHIVE", "Archive"),
                    ("AUTRE", "Autre"),
                ],
                db_index=True,
                default="AUTRE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Brouillon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("contenu", models.TextField(blank=True)),
                ("base_version", models.PositiveIntegerField(default=0)),
                ("derniere_frappe", models.DateTimeField(auto_now=True)),
                ("publie_le", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brouillons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="brouillons",
                        to="storage.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "brouillon",
                "ordering": ["-derniere_frappe"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("file", "author"), name="brouillon_unique_par_agent"
                    )
                ],
            },
        ),
    ]
