# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="root_folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_racine",
                to="storage.folder",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="agents",
                to="accounts.service",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["role"], name="accounts_us_role_1fa9a5_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["service"], name="accounts_us_service_19363c_idx"
            ),
        ),
    ]
