# Generated by Django 5.1.6 on 2026-08-31 06:45

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_initial"),
        ("storage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeoAsset",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="geo",
                        serialize=False,
                        to="storage.file",
                    ),
                ),
                (
                    "geo_format",
                    models.CharField(
                        choices=[
                            ("SHP", "Shapefile"),
                            ("GEOJSON", "GeoJSON"),
                            ("GEOTIFF", "GeoTIFF"),
                            ("KML", "KML"),
                            ("KMZ", "KMZ"),
                            ("GPX", "GPX"),
                            ("DXF", "DXF"),
                            ("DWG", "DWG"),
                            ("GPKG", "GeoPackage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("srid_source", models.IntegerField(blank=True, null=True)),
                (
                    "srid_declared",
                    models.IntegerField(
                        blank=True,
                        help_text="Projection corrigee manuellement lorsque la detection echoue.",
                        null=True,
                    ),
                ),
                (
                    "extent",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "centroid",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                ("geometry_type", models.CharField(blank=True, max_length=20)),
                ("feature_count", models.IntegerField(blank=True, null=True)),
                ("layer_names", models.JSONField(blank=True, default=list)),
                ("attributes_schema", models.JSONField(blank=True, default=dict)),
                ("raster_width", models.IntegerField(blank=True, null=True)),
                ("raster_height", models.IntegerField(blank=True, null=True)),
                ("raster_bands", models.IntegerField(blank=True, null=True)),
                ("pixel_size_x", models.FloatField(blank=True, null=True)),
                ("pixel_size_y", models.FloatField(blank=True, null=True)),
                ("preview_key", models.CharField(blank=True, max_length=500)),
                ("simplified_geojson", models.JSONField(blank=True, null=True)),
                (
                    "extraction_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("OK", "Complete"),
                            ("PARTIAL", "Partielle"),
                            ("FAILED", "Echouee"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("extraction_error", models.TextField(blank=True)),
                ("extracted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "donnee geospatiale",
            },
        ),
        migrations.CreateModel(
            name="ConversionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_format", models.CharField(max_length=10)),
                (
                    "target_format",
                    models.CharField(
                        choices=[
                            ("SHP", "Shapefile"),
                            ("GEOJSON", "GeoJSON"),
                            ("GEOTIFF", "GeoTIFF"),
                            ("KML", "KML"),
                            ("KMZ", "KMZ"),
                            ("GPX", "GPX"),
                            ("DXF", "DXF"),
                            ("DWG", "DWG"),
                            ("GPKG", "GeoPackage"),
                        ],
                        max_length=10,
                    ),
                ),
                ("target_srid", models.IntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("RUNNING", "En cours"),
                            ("DONE", "Terminee"),
                            ("FAILED", "Echouee"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversions",
                        to="storage.file",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "result_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversions_source",
                        to="storage.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "conversion",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GeoLayer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("style", models.JSONField(blank=True, default=dict)),
                ("z_index", models.IntegerField(default=0)),
                ("min_zoom", models.PositiveSmallIntegerField(default=0)),
                ("max_zoom", models.PositiveSmallIntegerField(default=22)),
                ("is_public", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="couches",
                        to="accounts.service",
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="couches",
                        to="storage.file",
                    ),
                ),
            ],
            options={
                "verbose_name": "couche cartographique",
                "ordering": ["z_index", "name"],
            },
        ),
    ]
